// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPnwTl63bOPPAbm53RsUfvQNOJTDCdw3M',
    appId: '1:10868495723:web:9f4c6b359baec1ae82682e',
    messagingSenderId: '10868495723',
    projectId: 'sundaart-sense',
    authDomain: 'sundaart-sense.firebaseapp.com',
    storageBucket: 'sundaart-sense.firebasestorage.app',
    measurementId: 'G-6J8W661X2T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkBmJ-APK7rcqyOg0655_WmC3-qck4BCQ',
    appId: '1:10868495723:android:002499fbdaf26cc382682e',
    messagingSenderId: '10868495723',
    projectId: 'sundaart-sense',
    storageBucket: 'sundaart-sense.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpmbmk5ZX873LOJO5Qqjn_ArgEHIi-EDA',
    appId: '1:10868495723:ios:7ca6500a2e70e93282682e',
    messagingSenderId: '10868495723',
    projectId: 'sundaart-sense',
    storageBucket: 'sundaart-sense.firebasestorage.app',
    iosBundleId: 'com.example.sundaartSense',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpmbmk5ZX873LOJO5Qqjn_ArgEHIi-EDA',
    appId: '1:10868495723:ios:7ca6500a2e70e93282682e',
    messagingSenderId: '10868495723',
    projectId: 'sundaart-sense',
    storageBucket: 'sundaart-sense.firebasestorage.app',
    iosBundleId: 'com.example.sundaartSense',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPnwTl63bOPPAbm53RsUfvQNOJTDCdw3M',
    appId: '1:10868495723:web:c6b4b9a23c88110982682e',
    messagingSenderId: '10868495723',
    projectId: 'sundaart-sense',
    authDomain: 'sundaart-sense.firebaseapp.com',
    storageBucket: 'sundaart-sense.firebasestorage.app',
    measurementId: 'G-16GE009Z9P',
  );
}
